---
version: "3.4"
services:
  truffle:
    build:
      context: .
      target: truffle
    ports:
      - 9545:9545
      - 24012:24012
    volumes:
      - .:/app:Z
      - /app/node_modules:Z
  # ganache:
  #   build:
  #     context: .
  #     target: ganache
  #   ports:
  #     - 8545:8545
  #   networks:
  #     - backend
